{
 "title": "New dashboard Copy",
 "time": { "from": "2018-09-09T22:48:31.738Z", "to": "2018-09-09T22:53:07.213Z" },
 "panels": [
  {
   "title": "Theads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "CodeRHost" }
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" }
      ],
      [
       { "params": [ "load5" ], "type": "field" }
      ],
      [
       { "params": [ "load15" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "CodeRHost" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col ($tag_interface)",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "recv" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ],
      [
       { "params": [ "free" ], "type": "field" }
      ],
      [
       { "params": [ "cached" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "iops_in_progress" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "io_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "memory_rss" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log size inc (speed)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "file" ], "type": "tag" }
     ],
     "measurement": "filestat",
     "select": [
      [
       { "params": [ "size_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "num_threads" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "jolokia_agent_url" ], "type": "tag" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" }
      ],
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Java Thread Count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "jolokia_agent_url" ], "type": "tag" }
     ],
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "ThreadCount" ], "type": "field" }
      ],
      [
       { "params": [ "PeakThreadCount" ], "type": "field" }
      ],
      [
       { "params": [ "TotalStartedThreadCount" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "jolokia_agent_url" ], "type": "tag" }
     ],
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" }
      ],
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "cpu_time" ], "type": "field" }
      ],
      [
       { "params": [ "cpu_time_user" ], "type": "field" }
      ],
      [
       { "params": [ "cpu_time_system" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FDS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "rlimit_num_fds_hard" ], "type": "field" }
      ],
      [
       { "params": [ "num_fds" ], "type": "field" }
      ],
      [
       { "params": [ "rlimit_num_fds_soft" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Context switch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "process_name" ], "type": "tag" }
     ],
     "measurement": "procstat",
     "select": [
      [
       { "params": [ "involuntary_context_switches" ], "type": "field" }
      ],
      [
       { "params": [ "voluntary_context_switches" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}